apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: hindelatache/config-service:latest
          ports:
            - containerPort: 8888
          env:
            - name: VAULT_HOST
              value: "vault"
            - name: VAULT_PORT
              value: "8200"
            - name: VAULT_TOKEN
              value: "hvs.t7nFP1cMLC8siCf0Gl3YciUQ"
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888