apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: hindelatache/config-service:latest
          ports:
            - containerPort: 8888
          env:
            - name: VAULT_HOST
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: VAULT_HOST
            - name: VAULT_PORT
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: VAULT_PORT
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token-secret
                  key: VAULT_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888