apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
data:
  # Config Server
  CONFIG_SERVER_URI: "http://config-service:8888"

  # Vault
  VAULT_HOST: "vault"
  VAULT_PORT: "8200"

  VAULT_ADDR: "http://vault:8200"        # add this
  VAULT_TOKEN: "hvs.t7nFP1cMLC8siCf0Gl3YciUQ"   # add this

  # Discovery
  EUREKA_URI: "http://discovery-service:8761/eureka"

  # Database
  POSTGRES_URL: "jdbc:postgresql://postgres:5432/test"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"