apiVersion: apps/v1
kind: Deployment
metadata:
  name: generateproject-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generateproject-service
  template:
    metadata:
      labels:
        app: generateproject-service
    spec:
      containers:
        - name: generateproject-service
          image: hindelatache/generateproject-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: CONFIG_SERVER_URI
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: EUREKA_URI
---
apiVersion: v1
kind: Service
metadata:
  name: generateproject-service
spec:
  selector:
    app: generateproject-service
  ports:
    - port: 8082
      targetPort: 8082