apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: hindelatache/recommendation-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: VAULT_ADDR
            - name: VAULT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: VAULT_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  selector:
    app: recommendation-service
  ports:
    - port: 8083
      targetPort: 8083