apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.15.0
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_LOCAL_CONFIG
              value: |
                ui = true
                storage "file" {
                  path = "/vault/data"
                }
                listener "tcp" {
                  address     = "0.0.0.0:8200"
                  tls_disable = true
                }
                api_addr = "http://0.0.0.0:8200"
          args: ["server"]
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
