spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}
            - id: recommandation-service
              uri: lb://recommandation-service
              predicates:
                - Path=/api/recommandation/**
              filters:
                - RewritePath=/api/recommandation/(?<segment>.*), /${segment}
            - id: generate-architecture
              uri: lb://recommandation-service
              predicates:
                - Path=/api/generate-architecture
              filters:
                - RewritePath=/api/generate-architecture, /generate-architecture
            - id: generate-project-service
              uri: lb://generate-project-service
              predicates:
                - Path=/api/generate/**
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
          trusted-proxies: ".*"
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus