pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'hindelatache'
        VAULT_TOKEN = credentials('vaultToken')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build All Services (Maven)') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Docker Build') {
            parallel {

                stage('Api Gateway') {
                    steps {
                        sh '''
                        docker build \
                        -t ${DOCKER_REGISTRY}/apigateway:${BUILD_NUMBER} \
                        -t ${DOCKER_REGISTRY}/apigateway:latest \
                        ./Services/ApiGateway
                        '''
                    }
                }

                stage('Auth Service') {
                    steps {
                        sh '''
                        docker build \
                        -t ${DOCKER_REGISTRY}/auth-service:${BUILD_NUMBER} \
                        -t ${DOCKER_REGISTRY}/auth-service:latest \
                        ./Services/Auth-service
                        '''
                    }
                }

                stage('Config Service') {
                    steps {
                        sh '''
                        docker build \
                        -t ${DOCKER_REGISTRY}/config-service:${BUILD_NUMBER} \
                        -t ${DOCKER_REGISTRY}/config-service:latest \
                        ./Services/ConfigService
                        '''
                    }
                }

                stage('Discovery Service') {
                    steps {
                        sh '''
                        docker build \
                        -t ${DOCKER_REGISTRY}/discoveryservice:${BUILD_NUMBER} \
                        -t ${DOCKER_REGISTRY}/discoveryservice:latest \
                        ./Services/discoveryService
                        '''
                    }
                }

                stage('Generate Project Service') {
                    steps {
                        sh '''
                        docker build \
                        -t ${DOCKER_REGISTRY}/generateproject-service:${BUILD_NUMBER} \
                        -t ${DOCKER_REGISTRY}/generateproject-service:latest \
                        ./Services/GenerateProjectService
                        '''
                    }
                }
                stage('Recommendation Service') {
                    steps {
                        sh '''
                        docker build \
                        -t ${DOCKER_REGISTRY}/recommendation-service:${BUILD_NUMBER} \
                        -t ${DOCKER_REGISTRY}/recommendation-service:latest \
                        ./Services/recommandation
                        '''
                    }
                }
            }
        }

        stage('Docker Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhubCredentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

                    docker push ${DOCKER_REGISTRY}/apigateway:${BUILD_NUMBER}
                    docker push ${DOCKER_REGISTRY}/apigateway:latest

                    docker push ${DOCKER_REGISTRY}/auth-service:${BUILD_NUMBER}
                    docker push ${DOCKER_REGISTRY}/auth-service:latest

                    docker push ${DOCKER_REGISTRY}/config-service:${BUILD_NUMBER}
                    docker push ${DOCKER_REGISTRY}/config-service:latest

                    docker push ${DOCKER_REGISTRY}/discoveryservice:${BUILD_NUMBER}
                    docker push ${DOCKER_REGISTRY}/discoveryservice:latest

                    docker push ${DOCKER_REGISTRY}/generateproject-service:${BUILD_NUMBER}
                    docker push ${DOCKER_REGISTRY}/generateproject-service:latest

                    docker push ${DOCKER_REGISTRY}/recommendation-service:${BUILD_NUMBER}
                    docker push ${DOCKER_REGISTRY}/recommendation-service:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes (K3s)') {
            steps {
                sh '''
                kubectl apply -f k8s/

                kubectl rollout restart deployment apigateway
                kubectl rollout restart deployment auth-service
                kubectl rollout restart deployment config-service
                kubectl rollout restart deployment discovery-service
                kubectl rollout restart deployment generateproject-service
                kubectl rollout restart deployment recommendation-service
                '''
            }
        }
    }

    post {
        success {
            echo 'SUCCESS: Full CI/CD pipeline completed (DockerHub + Kubernetes + Vault)'
        }

        failure {
            echo ' FAILED: Check logs'
        }

        always {
            sh 'docker logout || true'
        }
    }
}