server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: vault



  cloud:
    vault: # ← ADD THIS BLOCK
      authentication: TOKEN
      token: ${VAULT_TOKEN:myroot}
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: http
      kv:
        enabled: true
        backend: secret
        default-context: application
        profile-separator: '/'
        version: 2
    config:
      server:
        vault: # ← YOU ALREADY HAVE THIS
          authentication: TOKEN
          token: ${VAULT_TOKEN:myroot}
          host: ${VAULT_HOST:localhost}
          port: ${VAULT_PORT:8200}
          scheme: http
          kv-version: 2
eureka:
  client:
    register-with-eureka: false    # ← add this
    fetch-registry: false          # ← add this
    service-url:
      defaultZone: http://discovery-service:8761/eureka/


  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env